#define ONESHOT_TAP_TOGGLE 3

#define PERMISSIVE_HOLD

#define COMBO_TERM 25

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "jmaze/YnRMdQ"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

